name: Artisan Moss
favicon: null
layout_spectrum: 0.348330128705129
typography_spectrum: 0.5208424786105752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6291240437421948
  lightness: 0.17459546425379813
  saturation: 0.04998768540099263
  rhythmicContrast: 0.05283428099937737
purpose: []
