name: Artisan Moss
favicon: null
layout_spectrum: 0.24481
typography_spectrum: 0.5208424786105752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f6f9'
    - '#101115'
    - '#bbbcbe'
    - '#8f6d64'
    - '#387e09'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
